### PR TITLE
Add NPM publishing workflow

### PR DESCRIPTION
**Pull request by Mearman**

### CODE REVIEW

**Comment by Mearman** [comment]
made some assumptions about desired behaviours but a starting point for you @dglazkov

**Comment by dglazkov** [comment]
Thank you!! I defer to @aomarks on this.

**Comment by aomarks** [comment]
Nice work!

I like the idea of having a workflow we can trigger from GitHub that will publish packages. The things this doesn't give us that we'd get from adopting Changesets are 1. automatically publishing multiple packages, and 2. automatically managing CHANGELOG files. But this seems like an improvement, so I'll merge this. I assume you weren't able to test this for real, and I don't think we have the NPM token in our secrets that would make this work yet, but I can take a look at that.

**Comment by aomarks** [comment]
> only just noticed this got merged. has it been tested now @aomarks / @dglazkov ?

No I haven't gotten a chance to test it yet. But let's try it out next time we want to publish something!

**Pull request merged**
