### PR TITLE
Investigate default zoom event on UI

### PR DESCRIPTION
**Pull request by Mearman**
- resolves https://github.com/breadboard-ai/breadboard/issues/926

### CODE REVIEW

**Comment by Mearman** [comment]
@alexandraM98 could you just double check that the diff is correct now I've dropped the other commits, please?

**Comment by alexandraM98** [comment]
> @alexandraM98 could you just double check that the diff is correct now I've dropped the other commits, please?

Yes, that looks correct.

**Review by paullewis — CHANGES_REQUESTED** [review]
I think we want to do this in a slightly different way, though this is pretty close. I think we should only really do it on the graph renderer itself (not `window`), and I think we should add and remove it when the element is added & removed from the DOM. That way folks can still wheel-zoom in if they want to, and we're not leaving it lingering around as a behaviour.

So I would:

1. Create an `#onWheel` function that looks like what you have here: `#onWheel(e: WheelEvent) { e.preventDefault(); }` as a member of the class.
2. Add a bound copy of the listener function: `#onWheelBound = this.#onWheel.bind(this)` (I do this in [various other classes](https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard-ui/src/elements/splitter/splitter.ts#L49) if it's useful to see what I mean). This means we have a reference to the same function available for `addEventListener` and `removeEventListener`, and it is definitely bound to the instance. (This is not strictly necessary for a listener that doesn't refer to `this` internally, but it makes things internally consistent with the rest of the code, and if we ever change the behaviour of the function it's less likely to confuse matters.)
3. In the `connectedCallback`: `this.addEventListener('wheel', this.#onWheelBound)` and in the `disconnectedCallback`: `this.removeEventListener('wheel', this.#onWheelBound)`.

Hope that all makes sense!

**Review by paullewis — APPROVED** [review]

**Comment by Mearman** [comment]
@paullewis are you happy to merge this and https://github.com/breadboard-ai/breadboard/pull/965?

**Pull request merged**
