### PR TITLE
Convert GPT 3.5 Turbo board to Build API

### LINKED ISSUE #2817: Convert `./packages/example-boards/src/boards/playground/openai-gpt-35-turbo.ts` to Build API

### PR DESCRIPTION
**Pull request by TinaNikou**
Fixes #2817

Converted the OpenAI GPT 3.5 Turbo board to the new Build API.

The streaming has been removed for now, as the `transformStream` node from the `node-nursery-kit` is set to deprecated and I was not yet able to recreate the functionality using a `code` node or invoking a board.

### CODE REVIEW

**Comment by TinaNikou** [comment]
@aomarks @dglazkov Hello both!

I've converted this board without the streaming capabilities for now because I can't replicate the original streaming logic using a board or `code` node so far, and the `transformStream` node from the `node-nursery-kit`, which is used by the board pre-migration, is set to deprecated. I also noticed that the streaming also seems to be commented out in the Gemini Kit's `gemini-generator` board, so I was wondering if it's actually even built in now or just not working currently?

I wanted to ask if either of you have any suggestions for how to proceed with handling the streaming for this board? Any suggestions or guidance would be greatly appreciated :heart_decoration:

**Comment by dglazkov** [comment]
It's okay to not have streaming for now -- we will revisit the whole streaming machinery soon and make it work again.

**Comment by TinaNikou** [comment]
Okey doke! Thanks, Dimitri :heart:

**Review by dglazkov — APPROVED** [review]
LGTM!

**Pull request merged**
