### PR TITLE
2351 bbm.schema.json $id path is updated incorrectly

### PR DESCRIPTION
**Pull request by Mearman**
- resolves https://github.com/breadboard-ai/breadboard/issues/2351

### CODE REVIEW

**Review by dglazkov — COMMENTED** [review]
I see some build breakage.

Also 🙏🏻  smaller patches, smaller changes. I would rather review a bunch of five-liners than these.

**Review by dglazkov — APPROVED** [review]
LGTM!

**Comment by Mearman** [comment]
> Also 🙏🏻 smaller patches, smaller changes. I would rather review a bunch of five-liners than these.

@dglazkov Sorry, was aiming for it, but ended up being interconnected changes.

**Comment by paullewis** [comment]
Would you mind adding the license header to the files? Otherwise looks good to go!

**Pull request merged**
