### PR TITLE
Add schema from object node to JSON kit and migrate JSON kit tests to Node test runner

### PR DESCRIPTION
**Pull request by Mearman**
- closes https://github.com/breadboard-ai/breadboard/issues/1259

### CODE REVIEW

**Comment by dglazkov** [comment]
I thought we talked about this -- can we just use the JSON kit?

**Comment by Mearman** [comment]
Just saw your other reply on https://github.com/breadboard-ai/breadboard/issues/1259. Will do

**Review by dglazkov — APPROVED** [review]
LGTM 🥳

**Comment by dglazkov** [comment]
@Mearman ready to land?

**Pull request merged**
