### PR TITLE
[breadboard-cli] Improvements to debug and make CLI

### PR DESCRIPTION
**Pull request by PaulKinlan**
Debug:

+ Errors if you try and watch a folder where board JSON would be output
+ Warns if you set output and -n (no-save)
+ If your input is a directory then the output will map the same structure in the output folder
+ Extracts server to own file.

Make:

+ Outputs files by default to the filesystem, `-n to the console`
+ Adds the ability to make a directory
+ Errors if you try and watch a folder where board JSON would be output
+ Warns if you set output and -n (no-save)
+ If your input is a directory then the output will map the same structure in the output folder

### CODE REVIEW

**Comment by PaulKinlan** [comment]
@Mearman can you help me work out why this build fails? It's in one of the tests you wrote and I can't work out why

**Comment by PaulKinlan** [comment]
urgh - it now passed.

**Comment by Mearman** [comment]
@PaulKinlan I shall investigate regardless

**Comment by Mearman** [comment]
Interesting. I'm testing on https://github.com/breadboard-ai/breadboard/pull/620/commits/eb4de397d2b6a4a5042ed493d4dd96e9d200c992 as that's where the pipeline fails first.
In a container, with `npm run sync && npm run test`  I'm consistently getting:
```

> test
> wireit

                                                       
❌ [packages/node-nursery:test] exited with exit code 1. Output:


  ✔ template-parser › parametersFromTemplate returns an empty array when there are no parameters
  ✔ template-parser › parametersFromTemplate returns an array of parameters
  ✔ template-parser › parametersFromTemplate returns an array of unique parameters
  ✔ template-parser › parametersFromTemplate recognizes dashes and underscores
  ✔ template-parser › parametersFromTemplate ignores empty parameters
  ✔ template-parser › schemaFromParameters returns an valid schema when there are no parameters
  ✔ template-parser › schemaFromParameters returns an valid schema

  Uncaught exception in tests/cache.ts

  Error: /workspaces/breadboard/node_modules/sqlite3/build/Release/node_sqlite3.node: invalid ELF header

  › bindings (/workspaces/breadboard/node_modules/bindings/bindings.js:112:48)
  › Object.<anonymous> (/workspaces/breadboard/node_modules/sqlite3/lib/sqlite3-binding.js:1:37)

  ✘ tests/cache.ts exited with a non-zero exit code: 1
  ✔ vector-database › memory-vector-database
  ✔ vector-database › vector-database nodes
  ─

  9 tests passed
  1 uncaught exception
❌ 1 script failed.
```

After a `npm rebuild sqlite3` all tests consistently pass. Which my gut says is something putting the `WireIt` `node_modules` cache out of sync.

I have an idea. Investigating further.

**Comment by Mearman** [comment]
ok, @PaulKinlan, the overhaul is complete. It should handle old and new logic flexibly now. I also added some QoL stuff.
I'd like @aomarks, as resident `WireIt` guru, to look at the config, though, as I think that might have been what was masking the issues.

**Comment by PaulKinlan** [comment]
@Mearman just as a heads-up, I'm changing `breadboard make` - I think this is what is now causing the latest failures.

**Comment by PaulKinlan** [comment]
@Mearman fixed on my branch.

**Comment by Mearman** [comment]
@PaulKinlan Nice. I'll pull it over to my working branch

**Pull request merged**
