### PR TITLE
Add breadboard-python package

### PR DESCRIPTION
**Pull request by kex103**
Adds the breadboard-python package, which allows for breadboards to be defined in Python.

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to documentation are included in the PR

### CODE REVIEW

**Comment by dglazkov** [comment]
@aomarks shall we make a separate repo for Python?

**Comment by aomarks** [comment]
> @aomarks shall we make a separate repo for Python?

Kevin and I talked about it yesterday, I think a package in this repo is good for now. It will allow PRs that hit both the node and python code, which could be pretty useful. Integration test and such. Can always move it out later if we come up with a reason.

**Comment by dglazkov** [comment]
LGTM!

**Comment by kex103** [comment]
Whoops this ended up being squashed into one commit.
Addresses:
https://github.com/breadboard-ai/breadboard/issues/470.
https://github.com/breadboard-ai/breadboard/issues/464
https://github.com/breadboard-ai/breadboard/issues/463

**Pull request merged**
