### PR TITLE
renaming breadboard-cli-tools -> breadboard-cli

### PR DESCRIPTION
**Pull request by PaulKinlan**
Renames cli-tools

### CODE REVIEW

**Comment by dglazkov** [comment]
Could probably be just `cli` now ✨

**Comment by PaulKinlan** [comment]
@dglazkov I'm certainly open to that. However as I was changing things around I just noticed that the package name might become `@google-labs/cli`... which seems a little off.

**Comment by dglazkov** [comment]
Oh yeah, that's still to come. We can always rename later!

**Comment by PaulKinlan** [comment]
So - we're ok with renaming the folder to `cli` and then have it as `@google-labs/cli` (which in the future will chnage to something `@breadboard-ai/cli`?

**Comment by dglazkov** [comment]
oh, I meant -- you don't need to rename to `cli` right now. Can always do that later, once we have our package names organized.

**Comment by PaulKinlan** [comment]
cool. I'll keep this all as `breadboard-cli` everywhere and rename (it seems pretty easy to do).

**Pull request merged**
