### PR TITLE
Load Python files in make-graphs

### LINKED ISSUE #548: [breadboard-python] Load python board files in breadboard-web
Currently, breadboard-web loads typescript board files.

With breadboard-python, breadboard-web can also support loading python board files, allowing Python developers to use boards developed in Python on breadboard-web.

### PR DESCRIPTION
**Pull request by kex103**
Fixes #548 >

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to documentation are included in the PR

### CODE REVIEW

**Review by dglazkov — APPROVED** [review]
LGTM!

**Comment by PaulKinlan** [comment]
Can we land the python stuff in the importer in the cli (which then will implicitly work with the cli's `make`)? ... and then have breadboard web consume the `make` exports in the CLI...?

**Comment by kex103** [comment]
> Can we land the python stuff in the importer in the cli (which then will implicitly work with the cli's `make`)? ... and then have breadboard web consume the `make` exports in the CLI...?

Yeah, that would be fantastic.
I made an issue to track the breadboard-web loader: https://github.com/breadboard-ai/breadboard/issues/555

**Comment by kex103** [comment]
Looks like this PR always gets blocked because of the change to labs-prototype-ci.yml.
With the addition of python version, it looks like the check name changes, and now this PR gets blocked waiting for the old one, which never runs.

**Pull request merged**
