### PR TITLE
[openapi] Updating import to provide some schema.

### PR DESCRIPTION
**Pull request by PaulKinlan**
+ Adds `--input-file` to `breadboard run` so that you can add in required board parameters as a JSON file and not on the CLI
+ `breadboard import` the OpenAPI board now will dynamically generate inputs for parameters that are required.
+ `bradboard run` will use the default `args` if provided on the board.
+ `breadboard import` the OpenAPI board now uses secrets.
+ `breadboard debug` fixed the local-boards.
+ `breadboard` - removes log, and also assumes that missing types are strings.
+ `recipes` - all of the LLM recipes now use new api.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
@aomarks - just as a heads up, I had to merge main back into this branch and it looks like it's saying the affected packages by this change is a lot larger than the 2 I had submitted.... Is that going to cause issues?

**Comment by aomarks** [comment]
> @aomarks - just as a heads up, I had to merge main back into this branch and it looks like it's saying the affected packages by this change is a lot larger than the 2 I had submitted.... Is that going to cause issues?

I think what's happening is that, since your changeset has a `minor` revision to `breadboard`, it will get bumped from `0.8.0` to `0.9.0` on next release. In semver, when your leftmost digit is `0`, the second digit is actually treated like a breaking change (it's kind of like the change semantics all shift right; like it starts from the first non-zero digit). So, that means every package that depends on `breadboard` (which is almost all of them), will also need to be released the next time we publish, because their dependency semver constraints need to be bumped from `^0.8.0` to `^0.9.0` (because `^0.8.0` does not match `0.9.0`).

So, a bit confusingly, while a package is at `0.x.x`, we should use `patch` to add a new feature, and `minor` for a breaking change. We shouldn't use `major` unless we want to release `1.0.0`.

We could also bite the bullet and go straight to `1.0.0`. I'd actually be slightly in favor of that, because it means we get to have the full major/minor/patch distinction. Version numbers are free.

**Comment by PaulKinlan** [comment]
Got it - hmm. Sorry I merged this before your reply. Oof. ok, but I think it makes sense because I did change the functionality with the fix.

**Comment by dglazkov** [comment]
changeset sees all!

**Pull request merged**
