### PR TITLE
Added two tool boards to examples

### PR DESCRIPTION
**Pull request by dans-dev**
Adds 2 new tools to examples:
- Wiki Search: Searches wikipedia for relevant articles
- Get Wiki Article: Gets the article of a given title in a clean readable format

### CODE REVIEW

**Review by Mearman — APPROVED** [review]

**Comment by dglazkov** [comment]
Let's put these in playground boards for now. I want the example boards to have guides with them.

**Comment by dans-dev** [comment]
> Let's put these in playground boards for now. I want the example boards to have guides with them.

Sure thing, will do that for you today!

**Comment by dans-dev** [comment]
@dglazkov that has been sorted!

**Review by dglazkov — APPROVED** [review]
LGTM!

**Comment by dans-dev** [comment]
Ready to merge!

**Pull request merged**
