### PR TITLE
PALM_KEY assignment in README code snippet correction

### PR DESCRIPTION
**Pull request by davecampbell**
2 code snippets did not use { keys: } - noticed that as i was working through tutorial.
the actual tutorial.js files are OK.

### CODE REVIEW

**Comment by dglazkov** [comment]
Good find, @davecampbell!

**Comment by dglazkov** [comment]
@davecampbell Would love to take that PR -- could you sign the CLA?

**Comment by davecampbell** [comment]
@dglazkov - i thought i did, but it wasn't clear if that would trigger the CI.
some of these collab processes are new to me.

**Comment by dglazkov** [comment]
Awesome, thank you!

**Pull request merged**
